project:
  name: "VIS-RP01"
  version: "1.0.1"
  author: "Atanu Debnath"

paths:
  data_dir: "./data"
  output_dir: "./output"
  model_dir: "./models"

camera:
  id: 0
  width: 640
  height: 480
  output_filename: "output.jpg"
